/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The certificate issuer item containing certificate issuer metadata.
 */
@ApiModel(description = "The certificate issuer item containing certificate issuer metadata.")
public class CertificateIssuerItem {
  @SerializedName("id")
  private String id = null;

  @SerializedName("provider")
  private String provider = null;

  public CertificateIssuerItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Certificate Identifier.
   * @return id
  **/
  @ApiModelProperty(value = "Certificate Identifier.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CertificateIssuerItem provider(String provider) {
    this.provider = provider;
    return this;
  }

   /**
   * The issuer provider.
   * @return provider
  **/
  @ApiModelProperty(value = "The issuer provider.")
  public String getProvider() {
    return provider;
  }

  public void setProvider(String provider) {
    this.provider = provider;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertificateIssuerItem certificateIssuerItem = (CertificateIssuerItem) o;
    return Objects.equals(this.id, certificateIssuerItem.id) &&
        Objects.equals(this.provider, certificateIssuerItem.provider);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, provider);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertificateIssuerItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    provider: ").append(toIndentedString(provider)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

