/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.List;

/**
 * A list of keys that have been deleted in this vault.
 */
@ApiModel(description = "A list of keys that have been deleted in this vault.")

public class DeletedKeyListResult {
  @SerializedName("value")
  private List<DeletedKeyItem> value = null;

  @SerializedName("nextLink")
  private String nextLink = null;

   /**
   * A response message containing a list of deleted keys in the vault along with a link to the next page of deleted keys
   * @return value
  **/
  @ApiModelProperty(value = "A response message containing a list of deleted keys in the vault along with a link to the next page of deleted keys")
  public List<DeletedKeyItem> getValue() {
    return value;
  }

   /**
   * The URL to get the next set of deleted keys.
   * @return nextLink
  **/
  @ApiModelProperty(value = "The URL to get the next set of deleted keys.")
  public String getNextLink() {
    return nextLink;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DeletedKeyListResult deletedKeyListResult = (DeletedKeyListResult) o;
    return Objects.equals(this.value, deletedKeyListResult.value) &&
        Objects.equals(this.nextLink, deletedKeyListResult.nextLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, nextLink);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DeletedKeyListResult {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    nextLink: ").append(toIndentedString(nextLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

