/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * The attributes of an issuer managed by the Key Vault service.
 */
@ApiModel(description = "The attributes of an issuer managed by the Key Vault service.")
public class IssuerAttributes {
  @SerializedName("enabled")
  private Boolean enabled = null;

  @SerializedName("created")
  private Integer created = null;

  @SerializedName("updated")
  private Integer updated = null;

  public IssuerAttributes enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Determines whether the issuer is enabled.
   * @return enabled
  **/
  @ApiModelProperty(value = "Determines whether the issuer is enabled.")
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

   /**
   * Creation time in UTC.
   * @return created
  **/
  @ApiModelProperty(value = "Creation time in UTC.")
  public Integer getCreated() {
    return created;
  }

   /**
   * Last updated time in UTC.
   * @return updated
  **/
  @ApiModelProperty(value = "Last updated time in UTC.")
  public Integer getUpdated() {
    return updated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssuerAttributes issuerAttributes = (IssuerAttributes) o;
    return Objects.equals(this.enabled, issuerAttributes.enabled) &&
        Objects.equals(this.created, issuerAttributes.created) &&
        Objects.equals(this.updated, issuerAttributes.updated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, created, updated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssuerAttributes {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

