/*
 * KeyVaultClient
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.microsoft.identity.internal.test.keyvault.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Map;

/**
 * The storage account item containing storage account metadata.
 */
@ApiModel(description = "The storage account item containing storage account metadata.")

public class StorageAccountItem {
  @SerializedName("id")
  private String id = null;

  @SerializedName("resourceId")
  private String resourceId = null;

  @SerializedName("attributes")
  private StorageAccountAttributes attributes = null;

  @SerializedName("tags")
  private Map<String, String> tags = null;

   /**
   * Storage identifier.
   * @return id
  **/
  @ApiModelProperty(value = "Storage identifier.")
  public String getId() {
    return id;
  }

   /**
   * Storage account resource Id.
   * @return resourceId
  **/
  @ApiModelProperty(value = "Storage account resource Id.")
  public String getResourceId() {
    return resourceId;
  }

   /**
   * The storage account management attributes.
   * @return attributes
  **/
  @ApiModelProperty(value = "The storage account management attributes.")
  public StorageAccountAttributes getAttributes() {
    return attributes;
  }

   /**
   * Application specific metadata in the form of key-value pairs.
   * @return tags
  **/
  @ApiModelProperty(value = "Application specific metadata in the form of key-value pairs.")
  public Map<String, String> getTags() {
    return tags;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StorageAccountItem storageAccountItem = (StorageAccountItem) o;
    return Objects.equals(this.id, storageAccountItem.id) &&
        Objects.equals(this.resourceId, storageAccountItem.resourceId) &&
        Objects.equals(this.attributes, storageAccountItem.attributes) &&
        Objects.equals(this.tags, storageAccountItem.tags);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, resourceId, attributes, tags);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StorageAccountItem {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    resourceId: ").append(toIndentedString(resourceId)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

