# File: azure-pipelines\code-coverage\adal-code-cov.yml
# Description: Code coverage for adal
# Variable: 'mvnAccessToken' was defined in the Variables tab
# https://docs.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate
name: $(date:yyyyMMdd)$(rev:.r)

trigger: none

pr:
  branches:
    include:
      - '*'

variables:
- name: BuildParameters.jdkVersion
  value: 1.8
- name: BuildParameters.jdkArchitecture
  value: x64
- name: BuildParameters.javaHomeSelection
  value: JDKVersion
- name: robolectricSdkVersion
  value: 28

resources:
  repositories:
  - repository: self
    type: git
  - repository: common
    type: github
    name: AzureAD/microsoft-authentication-library-common-for-android
    ref: dev
    endpoint: ANDROID_GITHUB

jobs:
- job: adal_code_coverage
  displayName: ADAL Code Coverage
  pool:
    name: Hosted Windows 2019 with VS2019
  steps:
  - checkout: self
    displayName: Checkout ADAL Repository
    clean: true
    submodules: recursive
    persistCredentials: True
  - template: azure-pipelines/templates/steps/automation-cert.yml@common
  - task: JavaToolInstaller@0
    displayName: Use Java 8
    inputs:
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: Gradle@1
    displayName: Assemble Release
    inputs:
      tasks: clean adal:assembleLocal
      publishJUnitResults: false
      jdkVersion: $(BuildParameters.jdkVersion)
      jdkArchitecture: $(BuildParameters.jdkArchitecture)
      sqGradlePluginVersion: 2.0.1
  - task: Gradle@2
    displayName: Run ADAL Code Coverage
    inputs:
      tasks: adal:localDebugAdalUnitTestCoverageReport -Plabtest -ProbolectricSdkVersion=${{variables.robolectricSdkVersion}} -PcodeCoverageEnabled=true -PandroidTestsCodeCoverageEnabled=true
  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage Report
    inputs:
      summaryFileLocation: '$(Build.SourcesDirectory)\adal\build\reports\jacoco\localDebugAdalUnitTestCoverageReport\localDebugAdalUnitTestCoverageReport.xml'
      reportDirectory: '$(Build.SourcesDirectory)\adal\build\reports\jacoco\localDebugAdalUnitTestCoverageReport\html'
      javaHomeSelection: $(BuildParameters.javaHomeSelection)
      jdkVersion: 1.11
  - bash: |
      curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
      ./codecov.exe -v -t '$(codecovToken)' -B '$(System.PullRequest.SourceBranch)' -P '$(System.PullRequest.PullRequestNumber)' -f "./adal/build/reports/jacoco/localDebugAdalUnitTestCoverageReport/localDebugAdalUnitTestCoverageReport.xml"
    displayName: Upload Code Coverage to Codecov and the PR
