# File: azure-pipelines\auth-client\adal-instrumented-test.yml
# Description: Run instrumented test for ADAL.
name: Instrumented Tests

trigger:
- dev

resources:
 repositories:
 - repository: android-complete
   type: github
   name: AzureAD/android-complete
   ref: master
   endpoint: ANDROID_GITHUB

jobs:
- template: azure-pipelines/instrumented-tests/run-instrumented-tests.yml@android-complete
  parameters:
    projectName: adal
