name: Code coverage

on:
  pull_request:

env:
  ROBOELECTRIC_SDK_VERSION: 28

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
          architecture: 'x64'

      - name: Assemble
        run: ./gradlew clean adal:assembleLocal

      - name: Run Coverage
        run: ./gradlew adal:localDebugAdalUnitTestCoverageReport -ProbolectricSdkVersion=$ROBOELECTRIC_SDK_VERSION

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: ${{ github.workspace }}/adal/build/reports/jacoco/localDebugAdalUnitTestCoverageReport/localDebugAdalUnitTestCoverageReport.xml